- name: Install Redis package to get Redis repos
  yum:
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: Install  Redis
  yum:
    name: redis
    state: present
    enablerepo: 'remi'

- name: Update listen Ip Address
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start Redis
  systemd:
    name: redis
    state: started
    enabled: yes