- name: Demo On Variables
  hosts: all
  vars:
    URL: play.example.com
    URL: play2.example.com
  tasks:
    - name: Print Varibale
      debug:
        msg: URL = {{ URL }}
    - name: print from tasks
      vars:
        URL: task.example.com
      debug:
        msg: "{{ URL }}"

- name: Demo from Variable files
  hosts: all
  vars_files:
    - example-vars.yml
  tasks:
    - name: Print variable
      debug:
        msg: URL == {{ URL }}

- name: Demo from variables from Input
  hosts: all
  vars_prompt:
    - name: URL
      prompt: Enter URL
      private: no
  tasks:
    - name: URL
      debug:
        msg: URL == {{ URL }}

- name: Demo from variables from Inventory
  hosts: all
  tasks:
    - name: URL
      debug:
        msg: URL == {{ URL }}

- name: Print a fact
  hosts: all
  tasks:
    - name: Print a fact
      debug:
        msg: Log name == {{ ansible_user_dir }}

- name: Register a variable
  hosts: all
  tasks:
    - name: Grab how many users logged in
      shell: who | wc -l
      register: out
    - name: print out
      debug:
        msg: How many users logged in == {{ out.stdout }}

