- name: Demo On Variables
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Print Varibale
      debug:
        msg: URL = {{ URL }}
    - name: print from tasks
      vars:
        URL: task.example.com
      debug:
        msg: URL = {{ URL }}