#- name: Demo on tags
#  hosts: localhost
#  tasks:
#    - name: Demo on tags task level print aws
#      debug:
#        msg: AWS
#      tags:
#        - AWS
#
#
#    - name: Demo on tags task level print azure
#      debug:
#        msg: AZURE
#      tags:
#        - AZURE

- name: Demo on Tags play level
  hosts: localhost
  tags:
    - AWS
  tasks:
    - name: Demo on tags task level print aws
      debug:
        msg: AWS

- name: Demo on Tags play level
  hosts: localhost
  tags:
    - AZURE
  tasks:
    - name: Demo on tags task level print azure
      debug:
        msg: AZURE
