- name: Demo on conditions
  hosts: localhost
  vars:
    IS_RUN: false
    COUNT: 23
    NAME: pradeep
  tasks:
     ## Boolean Conditions
    - name: Run based on user input
      debug:
        msg: Hello World
      when: IS_RUN

    ## String condition
    - name: Print if there is ubuntu os
      debug:
        msg: Hello ubuntu
      when: ansible_distribution == "ubuntu"

    ## number condition
    - name: Print if count == 23
      debug:
        msg: Count == 23
      when: COUNT == 23

    - name: print my name
      debug:
        msg: print pradeep
      when: NAME == pradeep
