- name: setup the Roboshop Project -- Frontend Component
  hosts: FRONTEND
  become: yes
  tags:
    - frontend
  roles:
    - name: Load frontend role
      role: frontend

- name: setup the Roboshop Project -- MongoDB Component
  hosts: MONGODB
  become: yes
  tags:
    - mongodb
  roles:
    - name: Load mongodb role
      role: mongodb

- name: setup the Roboshop Project -- Catalogue Component
  hosts: CATALOGUE
  become: yes
  tags:
    - catalogue
  roles:
    - name: Load catalogue role
      role: catalogue

- name: setup the Roboshop Project -- redis Component
  hosts: REDIS
  become: yes
  tags:
    - redis
  roles:
    - name: Load redis role
      role: redis


- name: setup the Roboshop Project -- user Component
  hosts: USER
  become: yes
  tags:
    - user
  roles:
    - name: Load user role
      role: user


- name: setup the Roboshop Project -- cart Component
  hosts: CART
  become: yes
  tags:
    - cart
  roles:
    - name: Load cart role
      role: cart


- name: setup the Roboshop Project -- mysql Component
  hosts: MYSQL
  become: yes
  tags:
    - mysql
  roles:
    - name: Load mysql role
      role: mysql


- name: setup the Roboshop Project -- shipping Component
  hosts: SHIPPING
  become: yes
  tags:
    - shipping
  roles:
    - name: Load shipping role
      role: shipping


- name: setup the Roboshop Project -- rabbitmq Component
  hosts: RABBITMQ
  become: yes
  tags:
    - rabbitmq
  roles:
    - name: Load rabbitmq role
      role: rabbitmq



- name: setup the Roboshop Project -- payment Component
  hosts: PAYMENT
  become: yes
  tags:
    - payment
  roles:
    - name: Load payment role
      role: payment


