- name: setup the Roboshop Project -- Frontend Component
  hosts: FRONTEND
  become: yes
  tags:
    - frontend
  roles:
    - name: Load frontend role
      role: frontend

- name: setup the Roboshop Project -- MongoDB Component
  hosts: MONGODB
  become: yes
  tags:
    - mongodb
  roles:
    - name: Load mongodb role
      role: mongodb

- name: setup the Roboshop Project -- Catalogue Component
  hosts: CATALOGUE
  become: yes
  tags:
    - catalogue
  roles:
    - name: Load catalogue role
      role: catalogue

- name: setup the Roboshop Project -- redis Component
  hosts: REDIS
  become: yes
  tags:
    - redis
  roles:
    - name: Load redis role
      role: redis


- name: setup the Roboshop Project -- user Component
  hosts: USER
  become: yes
  tags:
    - user
  roles:
    - name: Load user role
      role: user


- name: setup the Roboshop Project -- cart Component
  hosts: CART
  become: yes
  tags:
    - cart
  roles:
    - name: Load cart role
      role: cart
