- name: setup the Roboshop Project
  hosts: FRONTEND
  become: yes
  roles:
    - name: Load frontend role
      role: frontend

- name: Start Nginx
  ansible.builtin.systemd:
    state: started
    name: nginx
    enabled: yes
