- name: setup the Roboshop Project
  hosts: FRONTEND
  become: yes
  roles:
    - name: Load frontend role
      role: frontend

- name: setup the Roboshop Project
  hosts: MONGODB
  roles:
    - name: Load mongodb role
      role: mongodb

