- name: Remove Old content
  ansible.builtin.file:
    path: "{{APP_DIR}}"
    state: absent

- name: Download Package From Git_Hub and Extract It
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/{{COMPONENT}}/archive/main.zip
    dest: "{{EXTRACT_DIR}}"
    remote_src: yes