- name: Install Maven
  yum:
    name:
      - maven
    state: installed

- name: Add roboshop user
  ansible.builtin.user:
    name: roboshop
    comment: Roboshop Project user

- name: Download package
  include_role:
    name: common
    tasks_from: download-from-github
  vars:
    APP_DIR: /home/roboshop/{{COMPONENT}}
    EXTRACT_DIR: /tmp

- name: Moving {{COMPONENT}}-main to {{COMPONENT}}
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/roboshop/{{COMPONENT}}/
    remote_src: yes
  become_user: roboshop

  ## mv clean package using shell command
- name: Build a package with maven
  shell: mvn clean package && mv target/{{COMPONENT}}-1.0.jar {{COMPONENT}}.jar
  args:
    chdir: /home/roboshop/{{COMPONENT}}
  become_user: roboshop

- name: Copy SystemD file
  copy:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: Start {{COMPONENT}} service
  ansible.builtin.systemd:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: yes
    daemon_reload: yes

