- name: Install Python
  yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: Add roboshop user
  ansible.builtin.user:
    name: roboshop
    comment: Roboshop Project user

- name: Download package
  include_role:
    name: common
    tasks_from: download-from-github
  vars:
    APP_DIR: /home/roboshop/{{COMPONENT}}
    EXTRACT_DIR: /tmp

- name: Moving {{COMPONENT}}-main to {{COMPONENT}}
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/roboshop/{{COMPONENT}}/
    remote_src: yes
  become_user: roboshop

- name: Install pythom dependencies
  pip:
    requirements: /home/roboshop/{{COMPONENT}}/
    executable: pip3

- name: Copy SystemD file
  copy:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: Start {{COMPONENT}} service
  ansible.builtin.systemd:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: yes
    daemon_reload: yes

